### ISSUE TITLE
Error When Running Quick Demo and also With Other Files

### ISSUE THREAD

**Issue by jastidinesh** [ditesh/node-poplib#13]
I have run the demo file and has ended up with an error. This is not there when I have used the previous version it seems to be some problem with the new version. The following is the result 
` ` 
C:\Users\Dinesh.node_modules\poplib>node demos/demo.js --host pop.gmail.com --p
ort 995 --username user@gmail.com --password potato --tls on --debug on --networ
kdebug on >> output.txt

C:\Users\Dinesh.node_modules\poplib\main.js:292
                });
                ^
SyntaxError: Unexpected token }
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\Dinesh.node_modules\poplib\demos\demo.js:28
:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
` `

**Comment by jastidinesh** [comment]
These are the changes which I made to the "main.js" file 
1. Remove the '}' in line number 295
2. Remove ',' in line number 631
And that seems to fix the problem. I'm using Avast as my antivirus and I'm getting the following error when I run the demo script.
` `
Server error occurred
[Error: SELF_SIGNED_CERT_IN_CHAIN]
` `
It is working fine if I disable Avast.

**Comment by ditesh** [comment]
Hey, could you try out the most recent 0.1.7 release (just released)?

**Comment by jastidinesh** [comment]
Its working now. No errors.

**Comment by ditesh** [comment]
Yeah, sorry about that :-)
